///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : intelligentwiper.h
/// SOFTWARE COMPONENT NAME           : IntelligentWiper
/// GENERATED DATE                    : 2025-08-07 19:04:14
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_AA_GEN_SOFTWARE_COMPONENT_INTELLIGENTWIPER_AA_H
#define PARA_AA_GEN_SOFTWARE_COMPONENT_INTELLIGENTWIPER_AA_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "intelligentwiper/aa/port/rportwiper.h"
 
#include "para/swc/port_pool.h"
 
namespace intelligentwiper
{
namespace aa
{
 
class IntelligentWiper
{
public:
    /// @brief Constructor
    IntelligentWiper();
    
    /// @brief Destructor
    ~IntelligentWiper();
    
    /// @brief Initialize software component
    bool Initialize();
    
    /// @brief Start software component
    void Start();
    
    /// @brief Terminate software component
    void Terminate();
    
    /// @brief Run software component
    void Run();
    
private:
    /// @brief Running status of software component
    bool m_running;
    
    /// @brief Pool of port
    ::para::swc::PortPool m_workers;
    
    /// @brief Logger for software component
    ara::log::Logger& m_logger;
    
    /// @brief Instance of Port {IntelligentWiper.RPortWiper}
    std::unique_ptr<intelligentwiper::aa::port::RPortWiper> m_RPortWiper;
};
 
} /// namespace aa
} /// namespace intelligentwiper
 
#endif /// PARA_AA_GEN_SOFTWARE_COMPONENT_INTELLIGENTWIPER_AA_H