///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : consumer.h
/// SOFTWARE COMPONENT NAME           : Consumer
/// GENERATED DATE                    : 2024-09-10 13:37:03
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_AA_GEN_SOFTWARE_COMPONENT_CONSUMER_AA_H
#define PARA_AA_GEN_SOFTWARE_COMPONENT_CONSUMER_AA_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "consumer/aa/port/rport.h"
 
#include "para/swc/port_pool.h"
#include <cstdint>
 
namespace consumer
{
namespace aa
{
 
class Consumer
{
public:
    /// @brief Constructor
    Consumer();
    
    /// @brief Destructor
    ~Consumer();
    
    /// @brief Initialize software component
    bool Initialize();
    
    /// @brief Start software component
    void Start();
    
    /// @brief Terminate software component
    void Terminate();
    
    /// @brief Run software component
    void Run();
    
private:
    /// @brief Running status of software component
    bool m_running;

    /// @brief Init Transparency;
    std::uint8_t initTransparency;
    
    /// @brief Pool of port
    ::para::swc::PortPool m_workers;
    
    /// @brief Logger for software component
    ara::log::Logger& m_logger;
    
    /// @brief Instance of Port {Consumer.RPort}
    std::unique_ptr<consumer::aa::port::RPort> m_RPort;
};
 
} /// namespace aa
} /// namespace consumer
 
#endif /// PARA_AA_GEN_SOFTWARE_COMPONENT_CONSUMER_AA_H