///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : r_bmsinfo.h
/// SOFTWARE COMPONENT NAME           : R_BmsInfo
/// GENERATED DATE                    : 2024-08-28 09:41:38
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_AA_GEN_SOFTWARE_COMPONENT_RPORT_BATTERYMONITOR_AA_R_BMSINFO_H
#define PARA_AA_GEN_SOFTWARE_COMPONENT_RPORT_BATTERYMONITOR_AA_R_BMSINFO_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "battery/bmsinfo/bmsinfosrv_proxy.h"
 
#include "ara/log/logger.h"
 
#include <mutex>
#include <thread>
#include <batterymonitor/aa/globalvariable_batterymonitor.h>
 
namespace batterymonitor
{
namespace aa
{
namespace port
{
 
class R_BmsInfo
{
public:
    /// @brief Constructor
    R_BmsInfo();
    
    /// @brief Destructor
    ~R_BmsInfo();

    ///
    bool IsReady2Run();
    
    /// @brief Start port
    void Start();
    
    /// @brief Terminate port
    void Terminate();
    
    /// @brief Subscribe event, ems_BmsInfo
    void Subscribeems_BmsInfo();
     
    /// @brief Stop event subscription, ems_BmsInfo
    void StopSubscribeems_BmsInfo();
     
    /// @brief Event receive handler, ems_BmsInfo
    void ReceiveEventems_BmsInfoTriggered();
     
    /// @brief Event receive handler, ems_BmsInfo
    void ReceiveEventems_BmsInfoCyclic();
     
    /// @brief Read event data, ems_BmsInfo
    void ReadDataems_BmsInfo(ara::com::SamplePtr<battery::bmsinfo::proxy::events::ems_BmsInfo::SampleType const> samplePtr);
     
    /// @brief Callback for event receiver, ems_BmsInfo
    void RegistReceiverems_BmsInfo();
    
private:
    /// @brief Callback for find service
    void Find(ara::com::ServiceHandleContainer<battery::bmsinfo::proxy::BmsInfoSrvProxy::HandleType> handles,
              ara::com::FindServiceHandle findHandle);
    
private:
    /// @brief Logger for this port
    ara::log::Logger& m_logger;
    
    /// @brief Flag of port status
    bool m_running;
    
    /// @brief Flag of find service status
    bool m_found;
    
    /// @brief Mutex for this port
    std::mutex m_mutex; 
    
    /// @brief AUTOSAR Port Interface
    std::shared_ptr<battery::bmsinfo::proxy::BmsInfoSrvProxy> m_interface;
    
    /// @brief Find service handle
    std::shared_ptr<ara::com::FindServiceHandle> m_findHandle;
};
 
} /// namespace port
} /// namespace aa
} /// namespace batterymonitor
 
#endif /// PARA_AA_GEN_SOFTWARE_COMPONENT_RPORT_BATTERYMONITOR_AA_R_BMSINFO_H