///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : r_lmpctrl.h
/// SOFTWARE COMPONENT NAME           : R_LmpCtrl
/// GENERATED DATE                    : 2024-08-28 09:41:38
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_AA_GEN_SOFTWARE_COMPONENT_RPORT_BATTERYMONITOR_AA_R_LMPCTRL_H
#define PARA_AA_GEN_SOFTWARE_COMPONENT_RPORT_BATTERYMONITOR_AA_R_LMPCTRL_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "lmp/control/eevpcontrolsoamim_proxy.h"
 
#include "ara/log/logger.h"
 
#include <mutex>
#include <thread>
#include <lmp/mode/impl_type_soamimmoodemode.h>
#include <batterymonitor/aa/globalvariable_batterymonitor.h>
 
namespace batterymonitor
{
namespace aa
{
namespace port
{
 
class R_LmpCtrl
{
public:
    /// @brief Constructor
    R_LmpCtrl();
    
    /// @brief Destructor
    ~R_LmpCtrl();
    
    /// @brief Start port
    void Start();
    
    /// @brief Terminate port
    void Terminate();

    ///
    void MethodRequestCyclic();
    
private:
    /// @brief Callback for find service
    void Find(ara::com::ServiceHandleContainer<lmp::control::proxy::EevpControlSoaMImProxy::HandleType> handles,
              ara::com::FindServiceHandle findHandle);
    
    
private:
    /// @brief Logger for this port
    ara::log::Logger& m_logger;
    
    /// @brief Flag of port status
    bool m_running;
    
    /// @brief Flag of find service status
    bool m_found;
    
    /// @brief Mutex for this port
    std::mutex m_mutex; 
    
    /// @brief AUTOSAR Port Interface
    std::shared_ptr<lmp::control::proxy::EevpControlSoaMImProxy> m_interface;
    
    /// @brief Find service handle
    std::shared_ptr<ara::com::FindServiceHandle> m_findHandle;
};
 
} /// namespace port
} /// namespace aa
} /// namespace batterymonitor
 
#endif /// PARA_AA_GEN_SOFTWARE_COMPONENT_RPORT_BATTERYMONITOR_AA_R_LMPCTRL_H